version: "3.4"


services:
    nginx-proxy:
        image: jwilder/nginx-proxy:alpine
        networks:
            tomcat-keycloak:
        ports:
            - "8080:80/tcp"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - /usr/share/nginx/html
            - /etc/nginx/certs
            - /etc/nginx/conf.d
            - /etc/nginx/vhost.d


    keycloak:
        image: jboss/keycloak:${KEYCLOAK_VERSION}
        networks:
            tomcat-keycloak:
                aliases:
                    - keycloak.site.example.com
        environment:
            PATH:              /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/jboss/keycloak/bin
            VIRTUAL_HOST:      keycloak.site.example.com
            DB_DATABASE:       ${DB_DATABASE}
            DB_USER:           ${DB_USER}
            DB_PASSWORD:       ${DB_PASSWORD}
            DB_VENDOR:         mysql
            DB_ADDR:           mysql
            JDBC_PARAMS:       useSSL=false
            KEYCLOAK_USER:     keycloak
            KEYCLOAK_PASSWORD: keycloak
        depends_on:
            - mysql
            - nginx-proxy


    tomcat:
        image: tomcat:8.5-jre10-keycloak
        build:
            context: build
            dockerfile: tomcat.Dockerfile
            args:
                - KEYCLOAK_VERSION=${KEYCLOAK_VERSION}
        networks:
            tomcat-keycloak:
                aliases:
                    - tomcat.site.example.com
        volumes:
            - ./data/tomcat/webapps/:/usr/local/tomcat/webapps/
        environment:
            VIRTUAL_HOST: tomcat.site.example.com
        depends_on:
            - keycloak
            - nginx-proxy


    wordpress:
        image: wordpress:4-apache
        networks:
            tomcat-keycloak:
                aliases:
                    - wordpress.site.example.com
        environment:
            VIRTUAL_HOST:          wordpress.site.example.com
            VIRTUAL_PROTO:         http
            WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            WORDPRESS_DB_NAME:     wp-keycloak
            WORDPRESS_DB_HOST:     mysql
        volumes:
            - ./data/wordpress-common/usr/local/etc/php/conf.d/wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini:ro
            - wordpress-data:/var/www/html
        depends_on:
            - mysql


    wp-cli:
        restart: "no"
        image: wordpress:cli
        networks:
            tomcat-keycloak:
        volumes:
            - wordpress-data:/var/www/html


    mysql:
        image: mysql:5.7
        networks:
            tomcat-keycloak:
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE:      ${DB_DATABASE}
            MYSQL_USER:          ${DB_USER}
            MYSQL_PASSWORD:      ${DB_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql


networks:
    tomcat-keycloak:


volumes:
    mysql-data:
        external: true
    wordpress-data:
        external: true
